# Generated by Django 2.1.4 on 2019-01-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20190128_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_model',
            name='git',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
