# Generated by Django 2.1.4 on 2019-01-29 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20190128_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='author_model',
            name='author_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author_model',
            name='git',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
