# Generated by Django 2.1.4 on 2019-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20190129_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_model',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default=[], null=True, related_name='_author_model_followed_by_+', to='users_app.Author_model'),
        ),
        migrations.AddField(
            model_name='author_model',
            name='following',
            field=models.ManyToManyField(blank=True, default=[], null=True, related_name='_author_model_following_+', to='users_app.Author_model'),
        ),
        migrations.AddField(
            model_name='author_model',
            name='following_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
