# Generated by Django 2.1.4 on 2019-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20190213_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_model',
            name='followers_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
