# Generated by Django 2.1.4 on 2019-02-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_author_model_followers_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_model',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='author_model',
            name='followers_number',
        ),
    ]
