# Generated by Django 2.1.4 on 2019-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_auto_20190213_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_model',
            name='following',
        ),
        migrations.AddField(
            model_name='author_model',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='following-authors+', to='users_app.Author_model'),
        ),
    ]
