# Generated by Django 2.1.4 on 2019-02-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_auto_20190131_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='body_edited',
        ),
        migrations.RemoveField(
            model_name='post_model',
            name='body_original',
        ),
        migrations.RemoveField(
            model_name='post_model',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='post_model',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='post_model',
            name='published_on',
        ),
        migrations.RemoveField(
            model_name='post_model',
            name='title_edited',
        ),
    ]
