# Generated by Django 2.1.4 on 2019-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0005_auto_20190201_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='body_original',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
    ]
