# Generated by Django 2.1.4 on 2019-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0006_auto_20190201_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='body_edited',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post_model',
            name='modified_on',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post_model',
            name='title_edited',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='body_original',
            field=models.TextField(),
        ),
    ]
