# Generated by Django 2.1.4 on 2019-02-01 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0007_auto_20190201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 46, 39, 708712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
