# Generated by Django 2.1.4 on 2019-02-01 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0008_auto_20190201_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 49, 42, 77740, tzinfo=utc)),
        ),
    ]
