# Generated by Django 2.1.3 on 2019-02-03 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0009_auto_20190201_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 18, 40, 12, 385628, tzinfo=utc)),
        ),
    ]
