# Generated by Django 2.1.3 on 2019-02-04 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0011_auto_20190204_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 3, 18, 44, 934007, tzinfo=utc)),
        ),
    ]
