# Generated by Django 2.1.4 on 2019-02-04 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0012_auto_20190204_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 5, 40, 14, 435400, tzinfo=utc)),
        ),
    ]
