# Generated by Django 2.1.4 on 2019-02-04 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0013_auto_20190204_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 6, 36, 23, 498012, tzinfo=utc)),
        ),
    ]
