<<<<<<< HEAD
# Generated by Django 2.1.3 on 2019-02-05 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0015_auto_20190205_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 17, 15, 55, 371365, tzinfo=utc)),
        ),
    ]
=======
# Generated by Django 2.1.3 on 2019-02-05 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0015_auto_20190205_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 17, 15, 55, 371365, tzinfo=utc)),
        ),
    ]
>>>>>>> e2a7d4736ca1b66fb4320489bbcb94f7f325937c
