# Generated by Django 2.1.4 on 2019-02-06 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0016_auto_20190205_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 4, 47, 38, 995308, tzinfo=utc)),
        ),
    ]
