# Generated by Django 2.1.4 on 2019-02-08 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20190129_1150'),
        ('blogs_app', '0017_auto_20190206_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to='users_app.Author_model'),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 59, 5, 859728, tzinfo=utc)),
        ),
    ]
