# Generated by Django 2.1.4 on 2019-02-13 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0020_auto_20190213_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 11, 35, 36, 377703, tzinfo=utc)),
        ),
    ]
