# Generated by Django 2.1.4 on 2019-02-13 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0022_auto_20190213_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 13, 4, 46, 399639, tzinfo=utc)),
        ),
    ]
